window.CHINA_FOOD_EN_NAMES = {
  "北京烤鸭": "Peking duck",
  "炸酱面": "Zhajiang noodles",
  "爆肚": "Quick-boiled tripe",
  "炒肝": "Beijing chaogan liver stew",
  "豆汁焦圈": "Fermented mung bean drink with fried rings",
  "门钉肉饼": "Mending meat pie",
  "铜锅涮肉": "Copper-pot lamb hot pot",
  "麻豆腐": "Fermented mung bean curd mash",
  "芥末墩": "Mustard cabbage rolls",
  "通州烧鲶鱼": "Tongzhou braised catfish",
  "小楼烧鲇鱼": "Xiaolou braised catfish",
  "驴打滚": "Soybean flour glutinous rice roll",
  "永宁豆腐": "Yongning tofu",
  "房山炸糕": "Fangshan fried rice cake",
  "张坊磨盘柿相关甜品": "Zhangfang persimmon desserts",
  "煎饼果子": "Tianjin jianbing guozi",
  "锅巴菜": "Guobacai cracker soup",
  "耳朵眼炸糕": "Erduoyan fried rice cake",
  "八珍豆腐": "Eight-treasure tofu",
  "十八街麻花": "Shibajie fried dough twists",
  "罾蹦鲤鱼": "Zengbeng carp",
  "武清豆腐丝": "Wuqing shredded tofu",
  "炸河虾": "Fried river shrimp",
  "海鲜八大碗": "Eight seafood bowls",
  "贴饽饽熬小鱼": "Stewed small fish with cornbread",
  "缸炉烧饼": "Clay-oven sesame flatbread",
  "金凤扒鸡": "Jinfeng braised chicken",
  "正定马家鸡": "Zhengding Maji chicken",
  "保定驴肉火烧": "Baoding donkey meat sandwich",
  "牛肉罩饼": "Beef-covered flatbread",
  "定州焖子": "Dingzhou starch sausage",
  "河间驴肉火烧": "Hejian donkey meat sandwich",
  "沧州羊肠汤": "Cangzhou lamb intestine soup",
  "金丝小枣糕点": "Golden-thread jujube pastries",
  "棋子烧饼": "Qizi sesame pastry",
  "鸿宴肘子": "Hongyan braised pork knuckle",
  "唐山麻糖": "Tangshan sesame candy",
  "承德凉粉": "Chengde mung bean jelly",
  "汽锅野味": "Steam-pot game stew",
  "南沙饼": "Nansha pastry",
  "四条包子": "Sitiao steamed buns",
  "海鲜蒸锅": "Steamed seafood pot",
  "长城饽椤饼": "Great Wall boluo leaf cake",
  "柴沟堡熏肉": "Chaigoubu smoked pork",
  "莜面窝子": "Oat noodle rolls",
  "怀安豆腐皮": "Huai'an tofu skin",
  "刀削面": "Knife-cut noodles",
  "过油肉": "Guoyourou stir-fried pork",
  "太原头脑": "Taiyuan tounao mutton soup",
  "羊杂割": "Mixed lamb offal soup",
  "老鼠窟元宵": "Laoshuku sweet rice dumplings",
  "大同刀削面": "Datong knife-cut noodles",
  "浑源凉粉": "Hunyuan cold jelly noodles",
  "大同兔头": "Datong spicy rabbit head",
  "大同铜火锅": "Datong copper hot pot",
  "广灵豆腐干": "Guangling dried tofu",
  "平遥牛肉": "Pingyao beef",
  "太谷饼": "Taigu cake",
  "祁县熏肉": "Qixian smoked pork",
  "榆次灌肠": "Yuci buckwheat sausage",
  "闻喜煮饼": "Wenxi boiled pastry",
  "稷山麻花": "Jishan fried dough twists",
  "解州羊肉泡馍": "Xiezhou lamb soup with bread",
  "长治羊汤": "Changzhi lamb soup",
  "壶关驴肉": "Huguan donkey meat",
  "潞城甩饼": "Lucheng tossed flatbread",
  "牛肉丸子面": "Beef meatball noodles",
  "洪洞蒸饭": "Hongtong steamed rice",
  "曲沃腊牛肉": "Quwo cured beef",
  "手把羊肉": "Hand-grabbed lamb",
  "奶茶": "Mongolian milk tea",
  "奶皮子": "Milk skin",
  "焙子": "Mongolian baked flatbread",
  "羊杂汤": "Lamb offal soup",
  "小肥羊火锅": "Little Sheep hot pot",
  "焖面": "Braised noodles",
  "固阳燕麦制品": "Guyang oat specialties",
  "烤全羊": "Roast whole lamb",
  "风干牛肉": "Air-dried beef",
  "列巴": "Russian-style rye bread",
  "俄式红肠": "Russian-style red sausage",
  "酸烩菜": "Sour vegetable stew",
  "猪骨头烩酸菜": "Pork bone and sauerkraut stew",
  "奶豆腐": "Milk tofu",
  "哈达饼": "Hada pastry",
  "对夹": "Chifeng meat sandwich",
  "赤峰锅包肉": "Chifeng sweet-sour crispy pork",
  "老边饺子": "Laobian dumplings",
  "马家烧麦": "Majia shaomai",
  "沈阳鸡架": "Shenyang chicken frame",
  "锅包肉": "Sweet-sour crispy pork",
  "大连焖子": "Dalian pan-fried starch cake",
  "海菜包子": "Seaweed steamed buns",
  "咸鱼饼子": "Salted fish with corn cakes",
  "沟帮子熏鸡": "Goubangzi smoked chicken",
  "锦州烧烤": "Jinzhou barbecue",
  "笔架山海鲜": "Bijia Mountain seafood",
  "海城馅饼": "Haicheng meat pie",
  "岫岩羊汤": "Xiuyan lamb soup",
  "抚顺麻辣拌": "Fushun spicy mixed bowl",
  "大伙房水库鱼": "Dahuofang Reservoir fish",
  "长春锅包肉": "Changchun sweet-sour crispy pork",
  "雪衣豆沙": "Snow-coated red bean paste",
  "鼎丰真糕点": "Dingfengzhen pastries",
  "延吉冷面": "Yanji cold noodles",
  "朝鲜族打糕": "Korean-style rice cake",
  "石板豆腐": "Stone-griddle tofu",
  "辣白菜": "Spicy kimchi",
  "吉林煎粉": "Jilin fried starch jelly",
  "松花湖鱼宴": "Songhua Lake fish banquet",
  "人参鸡": "Ginseng chicken",
  "通化葡萄酒相关甜品": "Tonghua wine desserts",
  "山野菜包子": "Wild vegetable steamed buns",
  "哈尔滨红肠": "Harbin red sausage",
  "俄式列巴": "Russian-style rye bread",
  "杀猪菜": "Northeast pork stew",
  "齐齐哈尔烤肉": "Qiqihar barbecue",
  "扎龙鱼宴": "Zhalong fish banquet",
  "佳木斯拌面": "Jiamusi mixed noodles",
  "铁锅炖大鹅": "Iron-pot stewed goose",
  "镜泊湖鱼宴": "Jingpo Lake fish banquet",
  "木耳炖鸡": "Chicken stew with wood ear mushrooms",
  "南翔小笼包": "Nanxiang soup dumplings",
  "生煎包": "Pan-fried soup buns",
  "梨膏糖": "Pear syrup candy",
  "本帮红烧肉": "Shanghainese red-braised pork",
  "糟钵头": "Zaobotou offal stew",
  "七宝老街汤团": "Qibao glutinous rice dumplings",
  "海棠糕": "Haitang rice cake",
  "下沙烧卖": "Xiasha shaomai",
  "三黄鸡": "Three-yellow chicken",
  "盐水鸭": "Nanjing salted duck",
  "鸭血粉丝汤": "Duck blood vermicelli soup",
  "活珠子": "Balut-style duck egg",
  "皮肚面": "Pork rind noodles",
  "松鼠桂鱼": "Squirrel-shaped mandarin fish",
  "蟹黄汤包": "Crab roe soup dumplings",
  "奥灶面": "Aozao noodles",
  "扬州炒饭": "Yangzhou fried rice",
  "大煮干丝": "Braised shredded tofu",
  "三丁包": "Three-dice steamed bun",
  "文思豆腐": "Wensi shredded tofu soup",
  "无锡酱排骨": "Wuxi sweet pork ribs",
  "阳山水蜜桃甜品": "Yangshan honey peach desserts",
  "玉兰饼": "Yulan stuffed rice cake",
  "镇江锅盖面": "Zhenjiang pot-lid noodles",
  "肴肉": "Zhenjiang crystal pork",
  "地锅鸡": "Clay-pan chicken",
  "烙馍": "Luomo flatbread",
  "龟打": "Xuzhou guiduo pastry",
  "淮安茶馓": "Huai'an fried tea crackers",
  "长鱼面": "Eel noodles",
  "西湖醋鱼": "West Lake vinegar fish",
  "东坡肉": "Dongpo pork",
  "龙井虾仁": "Shrimp with Longjing tea",
  "葱包烩": "Scallion pancake roll",
  "宁波汤圆": "Ningbo tangyuan",
  "红膏呛蟹": "Marinated red-roe crab",
  "年糕团": "Rice cake roll",
  "嘉兴粽子": "Jiaxing rice dumplings",
  "南湖菱": "Nanhu water caltrop",
  "酱鸭": "Soy-braised duck",
  "金华火腿": "Jinhua ham",
  "酥饼": "Flaky pastry",
  "汤包": "Soup dumplings",
  "温岭嵌糕": "Wenling stuffed rice cake",
  "梅花糕": "Plum blossom cake",
  "乌饭麻糍": "Black-rice mochi",
  "麦虾": "Mai Xia dough noodles",
  "温州鱼丸": "Wenzhou fish balls",
  "灯盏糕": "Dengzhan rice cake",
  "糯米饭": "Sticky rice",
  "臭鳜鱼": "Fermented mandarin fish",
  "毛豆腐": "Hairy tofu",
  "徽州饼": "Huizhou pastry",
  "庐州烤鸭": "Luzhou roast duck",
  "吴山贡鹅": "Wushan tribute goose",
  "三河米饺": "Sanhe rice dumplings",
  "淮南牛肉汤": "Huainan beef soup",
  "豆腐宴": "Tofu banquet",
  "格拉条": "Gela noodles",
  "太和板面": "Taihe banmian noodles",
  "枕头馍": "Pillow-shaped steamed bun",
  "安庆炒米": "Anqing puffed rice",
  "江毛水饺": "Jiangmao dumplings",
  "佛跳墙": "Buddha jumps over the wall",
  "荔枝肉": "Lychee-shaped sweet-sour pork",
  "鱼丸": "Fish balls",
  "锅边糊": "Guobian rice batter soup",
  "沙茶面": "Satay noodles",
  "土笋冻": "Sea worm jelly",
  "花生汤": "Peanut soup",
  "海蛎煎": "Oyster omelette",
  "闽南卤面": "Minnan braised noodles",
  "姜母鸭": "Ginger duck",
  "崇武鱼卷": "Chongwu fish rolls",
  "四果汤": "Four-fruit dessert soup",
  "卤面": "Braised noodles",
  "麻糍": "Glutinous rice mochi",
  "盐鸡": "Salt-baked chicken",
  "武夷熏鹅": "Wuyi smoked goose",
  "汀州豆腐干": "Tingzhou dried tofu",
  "南昌拌粉": "Nanchang mixed rice noodles",
  "瓦罐汤": "Clay-pot soup",
  "白糖糕": "White sugar rice cake",
  "九江茶饼": "Jiujiang tea cake",
  "庐山小白菜": "Lushan baby cabbage",
  "粉蒸肉": "Steamed pork with rice flour",
  "萍乡炒粉": "Pingxiang fried rice noodles",
  "莲花血鸭": "Lianhua blood duck",
  "烟熏腊肉": "Smoked cured pork",
  "赣南小炒鱼": "Southern Jiangxi stir-fried fish",
  "艾米果": "Aimi rice dumplings",
  "黄元米果": "Huangyuan rice cake",
  "井冈竹笋": "Jinggang bamboo shoots",
  "永丰霉鱼": "Yongfeng fermented fish",
  "九转大肠": "Nine-turn pork intestine",
  "油旋": "Youxuan spiral pastry",
  "甜沫": "Tianmo millet soup",
  "把子肉": "Bazi pork",
  "青岛海鲜": "Qingdao seafood",
  "鲅鱼饺子": "Mackerel dumplings",
  "青岛锅贴": "Qingdao potstickers",
  "德州扒鸡": "Dezhou braised chicken",
  "武城煊饼": "Wucheng xuanbing pastry",
  "淄博烧烤": "Zibo barbecue",
  "周村烧饼": "Zhoucun sesame crackers",
  "博山菜": "Boshan cuisine",
  "临沂炒鸡": "Linyi fried chicken",
  "单县羊汤": "Shanxian lamb soup",
  "煎饼卷大葱": "Pancake roll with scallions",
  "蓬莱小面": "Penglai small noodles",
  "鲅鱼水饺": "Mackerel dumplings",
  "海鲜卤面": "Seafood braised noodles",
  "郑州烩面": "Zhengzhou stewed noodles",
  "方中山胡辣汤": "Fangzhongshan hot pepper soup",
  "黄河大鲤鱼": "Yellow River carp",
  "葛记焖饼": "Geji braised flatbread",
  "开封灌汤包": "Kaifeng soup dumplings",
  "鲤鱼焙面": "Carp with crisp noodles",
  "炒凉粉": "Fried mung bean jelly",
  "桶子鸡": "Barrel chicken",
  "洛阳水席": "Luoyang water banquet",
  "牛肉汤": "Beef soup",
  "锅贴": "Potstickers",
  "牡丹饼": "Peony pastry",
  "逍遥镇胡辣汤": "Xiaoyaozhen hot pepper soup",
  "西华县烙馍": "Xihua flatbread",
  "固始鹅块": "Gushi goose chunks",
  "信阳热干面": "Xinyang hot dry noodles",
  "闷罐肉": "Clay-jar braised pork",
  "南湾鱼": "Nanwan fish",
  "热干面": "Hot dry noodles",
  "三鲜豆皮": "Three-delicacy tofu skin",
  "面窝": "Mianwo rice doughnut",
  "周黑鸭": "Zhou Black Duck",
  "潜江小龙虾": "Qianjiang crayfish",
  "炕洋芋": "Griddled potatoes",
  "土家腊肉": "Tujia cured pork",
  "白刹肥鱼": "Baisha fatty fish",
  "襄阳牛肉面": "Xiangyang beef noodles",
  "锅巴饭": "Crispy rice",
  "宜城大虾": "Yicheng prawns",
  "荆州鱼糕": "Jingzhou fish cake",
  "公安牛肉": "Gong'an beef",
  "洪湖藕汤": "Honghu lotus-root soup",
  "土家十大碗": "Tujia ten-bowl banquet",
  "榨广椒炒腊肉": "Cured pork with fermented chili",
  "合渣": "Hezha soybean stew",
  "长沙臭豆腐": "Changsha stinky tofu",
  "糖油粑粑": "Sugar-oil rice cakes",
  "剁椒鱼头": "Fish head with chopped chili",
  "辣椒炒肉": "Stir-fried pork with chili",
  "口味虾": "Spicy crayfish",
  "毛氏红烧肉": "Mao-style red-braised pork",
  "湘潭灯芯糕": "Xiangtan wick cake",
  "衡阳鱼粉": "Hengyang fish rice noodles",
  "耒阳坛子菜": "Leiyang jar-pickled vegetables",
  "湘西腊肉": "Xiangxi cured pork",
  "苗家酸鱼": "Miao sour fish",
  "蒿子粑粑": "Mugwort rice cake",
  "岳阳烧烤": "Yueyang barbecue",
  "平江香干": "Pingjiang spiced dried tofu",
  "洞庭银鱼": "Dongting whitebait",
  "广式早茶": "Cantonese morning tea",
  "虾饺": "Shrimp dumplings",
  "凤爪": "Chicken feet",
  "糯米鸡": "Sticky rice chicken parcels",
  "肠粉": "Rice noodle rolls",
  "煲仔饭": "Claypot rice",
  "白切鸡": "Poached chicken",
  "顺德鱼生": "Shunde raw fish salad",
  "双皮奶": "Double-skin milk pudding",
  "均安蒸猪": "Jun'an steamed pork",
  "烧鹅": "Roast goose",
  "潮汕牛肉火锅": "Chaoshan beef hot pot",
  "卤鹅": "Braised goose",
  "生腌": "Raw marinated seafood",
  "蚝烙": "Oyster omelette",
  "粿条汤": "Kway teow soup",
  "沙井生蚝": "Shajing oysters",
  "公明烧鹅": "Gongming roast goose",
  "湛江生蚝": "Zhanjiang oysters",
  "沙虫粥": "Sipunculus clam worm congee",
  "徐闻羊粥": "Xuwen lamb congee",
  "柳州螺蛳粉": "Liuzhou river-snail rice noodles",
  "柳州鸭脚煲": "Liuzhou duck-foot claypot",
  "桂林米粉": "Guilin rice noodles",
  "恭城油茶": "Gongcheng oil tea",
  "荔浦芋头扣肉": "Lipu taro pork",
  "南宁老友粉": "Nanning laoyou rice noodles",
  "酸嘢": "Guangxi pickled fruit snacks",
  "粉饺": "Rice noodle dumplings",
  "梧州纸包鸡": "Wuzhou paper-wrapped chicken",
  "龟苓膏": "Turtle jelly herbal dessert",
  "靖西酸粥": "Jingxi sour congee",
  "田东香芒甜品": "Tiandong mango desserts",
  "海南粉": "Hainan rice noodles",
  "清补凉": "Qingbuliang coconut dessert",
  "辣汤饭": "Spicy soup rice",
  "椰子饭": "Coconut rice",
  "椰子冻": "Coconut jelly",
  "和乐蟹": "Hele crab",
  "文昌鸡": "Wenchang chicken",
  "抱罗粉": "Baoluo rice noodles",
  "后安粉": "Hou'an rice noodles",
  "兴隆咖啡糕点": "Xinglong coffee pastries",
  "重庆火锅": "Chongqing hot pot",
  "重庆小面": "Chongqing noodles",
  "山城小汤圆": "Chongqing mini tangyuan",
  "红油抄手": "Wontons in chili oil",
  "毛血旺": "Maoxuewang spicy blood curd stew",
  "辣子鸡": "Spicy chicken with chilies",
  "蹄花汤": "Pork trotter soup",
  "南山泉水鸡": "Nanshan spring-water chicken",
  "豆花饭": "Tofu pudding with rice",
  "江津米花糖": "Jiangjin puffed rice candy",
  "酸菜鱼": "Sichuan pickled cabbage fish",
  "麻婆豆腐": "Mapo tofu",
  "回锅肉": "Twice-cooked pork",
  "担担面": "Dandan noodles",
  "龙抄手": "Long chaoshou wontons",
  "钵钵鸡": "Bobo chicken skewers",
  "三大炮": "Three cannon rice cakes",
  "自贡冷吃兔": "Zigong cold rabbit",
  "自贡盐帮菜": "Zigong salt-trader cuisine",
  "跳水鱼": "Tiaoshui spicy fish",
  "乐山甜皮鸭": "Leshan sweet-skin duck",
  "跷脚牛肉": "Qiaojiao beef soup",
  "宜宾燃面": "Yibin burning noodles",
  "李庄白肉": "Lizhuang sliced pork",
  "绵阳米粉": "Mianyang rice noodles",
  "江油肥肠": "Jiangyou pork intestines",
  "肠旺面": "Changwang noodles",
  "丝娃娃": "Siwawa vegetable rolls",
  "花溪牛肉粉": "Huaxi beef rice noodles",
  "恋爱豆腐果": "Grilled tofu cubes",
  "遵义羊肉粉": "Zunyi lamb rice noodles",
  "豆花面": "Tofu pudding noodles",
  "茅台酒心糖": "Moutai liquor-filled candy",
  "酸汤鱼": "Sour soup fish",
  "苗族腌鱼": "Miao pickled fish",
  "都匀冲冲糕": "Duyun chongchong cake",
  "酸汤粉": "Sour soup rice noodles",
  "过桥米线": "Crossing-the-bridge rice noodles",
  "汽锅鸡": "Steam-pot chicken",
  "鲜花饼": "Flower pastry",
  "泡鲁达": "Paoluda coconut milk dessert",
  "大理乳扇": "Dali milk fan cheese",
  "饵块": "Erkuai rice cake",
  "酸辣鱼": "Sour-spicy fish",
  "傣味舂鸡脚": "Dai-style pounded chicken feet",
  "菠萝饭": "Pineapple rice",
  "香茅草烤鱼": "Lemongrass grilled fish",
  "腾冲大救驾": "Tengchong fried rice cake",
  "稀豆粉": "Thin pea porridge",
  "藏面": "Tibetan noodles",
  "甜茶": "Tibetan sweet tea",
  "酥油茶": "Butter tea",
  "牦牛肉火锅": "Yak meat hot pot",
  "藏包子": "Tibetan steamed buns",
  "石锅鸡": "Stone-pot chicken",
  "松茸炖鸡": "Matsutake chicken stew",
  "藏香猪": "Tibetan fragrant pork",
  "青稞饼": "Highland barley cake",
  "糌粑": "Tsampa",
  "风干牦牛肉": "Air-dried yak meat",
  "朋必": "Pengbi pea jelly",
  "青稞酒": "Highland barley wine",
  "酥油糌粑": "Tsampa with butter",
  "羊肉汤": "Lamb soup",
  "风干羊肉": "Air-dried lamb",
  "肉夹馍": "Roujiamo meat sandwich",
  "羊肉泡馍": "Pita bread soaked in lamb soup",
  "油泼面": "Oil-splashed noodles",
  "甑糕": "Steamed glutinous rice cake",
  "镜糕": "Mirror rice cake",
  "biangbiang面": "Biangbiang noodles",
  "宝鸡擀面皮": "Baoji rolled cold noodles",
  "臊子面": "Saozi noodles",
  "醋粉": "Vinegar rice noodles",
  "咸阳锅盔": "Xianyang guokui flatbread",
  "蓼花糖": "Liaohua candy",
  "潼关肉夹馍": "Tongguan roujiamo",
  "华阴大刀面": "Huayin broad-knife noodles",
  "榆林拼三鲜": "Yulin three-delicacy platter",
  "羊肉面": "Lamb noodles",
  "兰州牛肉面": "Lanzhou beef noodles",
  "酿皮子": "Lanzhou cold rice noodles",
  "甜醅子": "Fermented sweet barley",
  "天水呱呱": "Tianshui guagua buckwheat jelly",
  "浆水面": "Sour jiangshui noodles",
  "花牛苹果甜品": "Huaniu apple desserts",
  "靖远羊羔肉": "Jingyuan lamb",
  "黄河鱼": "Yellow River fish",
  "驴肉黄面": "Donkey meat yellow noodles",
  "杏皮水": "Apricot peel drink",
  "炕锅羊排": "Kangguo lamb ribs",
  "青海老酸奶": "Qinghai yogurt",
  "尕面片": "Ga noodle pieces",
  "狗浇尿": "Goujiaoniao griddled pancake",
  "手抓牦牛肉": "Hand-grabbed yak meat",
  "土火锅": "Earthen hot pot",
  "酿皮": "Qinghai liangpi",
  "甜醅": "Fermented sweet barley",
  "筏子面肠": "Fazi stuffed noodle sausage",
  "手抓羊肉": "Hand-grabbed lamb",
  "烩小吃": "Ningxia mixed stew",
  "羊肉臊子面": "Lamb saozi noodles",
  "中卫硒砂瓜": "Zhongwei selenium melon",
  "中卫蒿子面": "Zhongwei haozi noodles",
  "吴忠早茶": "Wuzhong morning tea",
  "羊杂碎": "Lamb offal soup",
  "油香馓子": "Youxiang fried dough twists",
  "大盘鸡": "Big-plate chicken",
  "手抓饭": "Xinjiang pilaf",
  "烤羊肉串": "Lamb skewers",
  "椒麻鸡": "Peppery shredded chicken",
  "烤包子": "Baked lamb buns",
  "馕坑烤肉": "Tandoor-roasted lamb",
  "拉条子": "Laghman pulled noodles",
  "馕": "Naan bread",
  "手抓肉": "Hand-grabbed meat",
  "哈萨克奶茶": "Kazakh milk tea",
  "马奶酒": "Kumis",
  "葡萄架下手抓饭": "Pilaf under grape trellises",
  "叉烧": "Char siu barbecue pork",
  "云吞面": "Wonton noodles",
  "菠萝油": "Pineapple bun with butter",
  "丝袜奶茶": "Hong Kong milk tea",
  "鱼蛋": "Curry fish balls",
  "钵仔糕": "Put chai pudding",
  "烧腊": "Cantonese roast meats",
  "盆菜": "Poon choi basin feast",
  "鸡蛋仔": "Egg waffles",
  "冻柠茶": "Iced lemon tea",
  "葡式蛋挞": "Portuguese egg tart",
  "猪扒包": "Pork chop bun",
  "杏仁饼": "Almond cookies",
  "木糠布甸": "Serradura pudding",
  "葡国鸡": "Portuguese chicken",
  "水蟹粥": "Crab congee",
  "马介休": "Bacalhau codfish",
  "卤肉饭": "Braised pork rice",
  "蚵仔煎": "Oyster omelette",
  "大肠包小肠": "Small sausage in big sausage",
  "珍珠奶茶": "Bubble tea",
  "虱目鱼粥": "Milkfish congee",
  "担仔面": "Danzai noodles",
  "虾卷": "Shrimp rolls",
  "盐酥鸡": "Taiwanese popcorn chicken",
  "木瓜牛奶": "Papaya milk",
  "六合夜市小吃": "Liuhe Night Market snacks",
  "肉圆": "Taiwanese meatball dumplings"
};
